### ISSUE TITLE
Parameter selection

### ISSUE THREAD

**Issue by btupper** [SeascapeScience/gom-series#11]
SST (all regions)
CHLOR (all regions)
Climate Indices
GHCN 00272174  TMIN, TMAX, PRCP
     001990736
     00171628
USGS 1059000
     1022500
HAB east and west
PCI anom fall+spring log

Nutrients (Nick)
Calanus (Camille)
Salinity Glories ?

**Comment by jevanilla** [comment]
See pull request #13
