### ISSUE TITLE
Surprise plot updates

### ISSUE THREAD

**Issue by btupper** [SeascapeScience/gom-series#21]
Surprise plot

- [x] Order categorical colors red white blue gray order

- [x] Remove y-axis "Parameters" label

- [x] Angle the y-axis text for readablility

- [ ] More meaningful names for rows ( see https://docs.google.com/spreadsheets/d/1gMhKgIrCzw1wRYcFyIQ2hCxHkqOPiirZMDXvgsGNZvQ/edit#gid=0 )

**Comment by btupper** [comment]
@chross22 except for better names, how does this look?  Do we ditch the plot title?

![test-surprise](https://github.com/SeascapeScience/gom-series/assets/5097791/6b4c3417-0d94-4e52-b4de-aab0f0c886ea)

**Comment by chross22** [comment]
That looks great! I would get rid of the title.

**Comment by SeascapeScience** [comment]
Looks great. 
Why do the time series start so late? 
Cal index, PCI, HAB index should all go further back, right? And the climate indices?
This is the 10 year sliding window? Are we losing years by requiring the full 10 years of data?
Sorry to inundate!

**Comment by btupper** [comment]
OK - for the READMEs I'll leave the title on, but for publication we can set the argument to NULL to suppress it `plot_surprise(blah, blah, blah, title = NULL)`

**Comment by btupper** [comment]
These are question for the wider group, but the code is set up so the date start and window are arguments.  The particular plot I showed is a 20y window, and the start date is 1970. Try tweaking the README to your satisfaction.

**Comment by jevanilla** [comment]
It looks like the PRCP variable(s) are missing. They aren't coming into the network plots for me either. I'll look into this...

**Comment by SeascapeScience** [comment]
Something weird is happening with the precip data. It's appearing in the upper plot, but not in the surprise plot.

**Comment by btupper** [comment]
Stupid computers - any luck tracking that down @jevanilla ?

**Comment by btupper** [comment]
It has to to with the `purge_empty = TRUE/FALSE` argument to `plot_surprise()`  If TRUE (the default) then when a column is NA everywhere it is dropped.  Now, the question really is why does `PRCP` yield NA from the `surprise()` function.  Below I walk through with just the PRCP values with 'median' treatment.

``` r
source("setup.R")
#> here() starts at /mnt/s1/projects/ecocast/projects/nrecord/gom-series

x = read_export(by = 'year', 
                standardize = TRUE,     # <---- note!
                selection = read_target_vars(treatment = "median")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  dplyr::select(contains("PRCP"))

summary(x)
#>  GHCN.USC00272174.PRCP.median GHCN.USC00190736.PRCP.median
#>  Min.   :-0.4031              Min.   : NA                 
#>  1st Qu.:-0.4031              1st Qu.: NA                 
#>  Median :-0.4031              Median : NA                 
#>  Mean   :-0.4031              Mean   :NaN                 
#>  3rd Qu.:-0.4031              3rd Qu.: NA                 
#>  Max.   :-0.4031              Max.   : NA                 
#>  NA's   :1                    NA's   :53                  
#>  GHCN.USC00171628.PRCP.median
#>  Min.   : NA                 
#>  1st Qu.: NA                 
#>  Median : NA                 
#>  Mean   :NaN                 
#>  3rd Qu.: NA                 
#>  Max.   : NA                 
#>  NA's   :53


y = read_export(by = 'year', 
                standardize = FALSE,  # <---- note, now raw values!
                selection = read_target_vars(treatment = "median")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  dplyr::select(contains("PRCP"))

summary(y)
#>  GHCN.USC00272174.PRCP.median GHCN.USC00190736.PRCP.median
#>  Min.   :0                    Min.   :0                   
#>  1st Qu.:0                    1st Qu.:0                   
#>  Median :0                    Median :0                   
#>  Mean   :0                    Mean   :0                   
#>  3rd Qu.:0                    3rd Qu.:0                   
#>  Max.   :0                    Max.   :0                   
#>  NA's   :1                                                
#>  GHCN.USC00171628.PRCP.median
#>  Min.   :0                   
#>  1st Qu.:0                   
#>  Median :0                   
#>  Mean   :0                   
#>  3rd Qu.:0                   
#>  Max.   :0                   
#>  NA's   :5

s = surprise(y, win = 20)

summary(s)
#>  GHCN.USC00272174.PRCP.median GHCN.USC00190736.PRCP.median
#>  Min.   : NA                  Min.   : NA                 
#>  1st Qu.: NA                  1st Qu.: NA                 
#>  Median : NA                  Median : NA                 
#>  Mean   :NaN                  Mean   :NaN                 
#>  3rd Qu.: NA                  3rd Qu.: NA                 
#>  Max.   : NA                  Max.   : NA                 
#>  NA's   :53                   NA's   :53                  
#>  GHCN.USC00171628.PRCP.median
#>  Min.   : NA                 
#>  1st Qu.: NA                 
#>  Median : NA                 
#>  Mean   :NaN                 
#>  3rd Qu.: NA                 
#>  Max.   : NA                 
#>  NA's   :53
```

<sup>Created on 2023-08-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
