### ISSUE TITLE
climate indices

### ISSUE THREAD

**Issue by btupper** [SeascapeScience/gom-series#9]
I'm thinking that each read_xyz() should return a tibble with `date` (2020-01-01) and `name` (amo, nao or gis) and `index` (the value).  Then have one function, read_climate_indices() that row binds them (so, long format).  We could add a keyword like `form = c("long", "wide")[1]) so a wide format could be had easily for export.  

Also, we should probably check for complete intervals when averaging from month to year rather than just dropping all NAs.  I don't think it is the same thing.

**Comment by btupper** [comment]
@jevanilla I think it is harmonized with the other datasets now.  Please check my knots.  I decided that it was easier (lazier?) to just bind all three together form the get go to do the aggregation etc.

**Comment by jevanilla** [comment]
@btupper Good call. It's working for me now, probably good to close this.

**Comment by btupper** [comment]
Great - thanks.  It's still a bit awkward to have some datasets for which we can computed distributions for aggregation (the `sixnum()` stuff) while others don't have that.  It just is, I guess.  We'll deal with that downstream, but for now we have as much consistency as we can provide.
